# Generated by Django 3.1.7 on 2021-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenteruser',
            name='is_blogger',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
